#ifndef CPP_PRACTICE_SRC_COMPONENT_UTIL_COMMON_H_
#define CPP_PRACTICE_SRC_COMPONENT_UTIL_COMMON_H_

#define COMPONENT_SPACE_START namespace component {
#define COMPONENT_SPACE_END }
#define USING_COMPONENT using namespace component;

#endif //CPP_PRACTICE_SRC_COMPONENT_UTIL_COMMON_H_
